### ISSUE TITLE
Decouple of rxJava and rxAndroid

### ISSUE THREAD

**Issue by pedrofsn** [bobekos/SimpleBarcodeScanner#11]
Theoretically it can be made but I haven't analysed code yet. 

My idea is put this lib to work without embbed dependecies of rx. So on the future version will be need add rx dependencies or not/others - if like. Do you think is it possible @yuriy-budiyev?

**Comment by bobekos** [comment]
@pedrofsn 

Why should you want to do that? This library is based on RxJava. If you want to decouple the used RxJava/RxAndroid Version you should fork this lib and replace the gradle dependencies keywords from "api" to "implementation". On the other hand there is a google [sample](https://github.com/googlesamples/android-vision/tree/master/visionSamples/barcode-reader) without the usage of rx dependencies at all.

**Comment by bobekos** [comment]
close due inactivity
