### ISSUE TITLE
Is there any way to completely release the camera and then retrieve it again?

### ISSUE THREAD

**Issue by renanferrari** [bobekos/SimpleBarcodeScanner#14]
My app has a single screen where I can use the camera to read barcodes or use another external device to do so, like a physical barcode scanner connected via USB. 

The user needs to be able to switch between these two "modes", meaning that the app needs the ability to turn off the camera and then turn it on again if necessary, all within the same screen.

Some of those external devices won't work if they detect the camera is not released, meaning I need a way to completely release the camera before using those devices.

Initially, I thought the camera would be released upon disposing the BarcodeView's Observable subscription, but as far as I understand now, this only happens when the BarcodeView itself is completely destroyed.

How can I completely release the camera and retrieve it again if necessary using this library?

**Comment by bobekos** [comment]
Hi @renanferrari ,

thank you for submit this bug. Yeah you are right, the camera should be released when the subscription gets disposed. There was a mistake in the last update. I fixed the bug and released a new version. Can you test it now?

**Comment by renanferrari** [comment]
@bobekos It's working fine now, thank you for fixing it!

**Comment by Abdallah4021** [comment]
Hi @bobekos,  

mDisposable?.dispose() it's working well with Android 11, but it does not release the camera on Android 8.1.0  !
