### ISSUE TITLE
Activity closes after few scans without any crash logs 

### ISSUE THREAD

**Issue by vishwajit-palankar** [bobekos/SimpleBarcodeScanner#15]
Hi,
I have used your library and I am using it for continuously scanning QR codes. It scans perfectly for few and then suddenly the activity is killed without any crash logs or anything. It doesn't have any particular pattern sometimes it closes after 1000+ or sometimes it closes at 40.

**Comment by bobekos** [comment]
I am going to archive this repo. Unfortunately, I don't have the time to actively maintain it
