### ISSUE TITLE
Getting this error after migrating to androidx Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'

### ISSUE THREAD

**Issue by Krishnasony** [bobekos/SimpleBarcodeScanner#16]
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.bobekos:SimpleBarcodeScanner:1.0.23: Skipped due to earlier error

**Comment by bobekos** [comment]
I am going to archive this repo. Unfortunately, I don't have the time to actively maintain it
