### ISSUE TITLE
Sometimes scans non existent barcodes

### ISSUE THREAD

**Issue by tronne** [bobekos/SimpleBarcodeScanner#17]
It's something very weird, while waiting for the next scan and with the camera on, sometimes catches codes like 6549151343733,  6935933646060.. but for sure there's no any bar code, it could happen pointing to the floor, to a wall or whatever object. It happens to me randomly every 1-10 min

**Comment by bobekos** [comment]
I am going to archive this repo. Unfortunately, I don't have the time to actively maintain it
